### ISSUE TITLE
Buttons turn black when you click them

### ISSUE THREAD

**Issue by Zod-** [fballs/old.instasync#2]
And stay black until you click again?

![image](https://cloud.githubusercontent.com/assets/5775094/7163949/51f277c8-e39d-11e4-8478-155683adeb1c.png)
![image](https://cloud.githubusercontent.com/assets/5775094/7163953/5a2990e8-e39d-11e4-9330-26748a171f28.png)
![image](https://cloud.githubusercontent.com/assets/5775094/7163963/6134c18c-e39d-11e4-8ee3-feb93dd6101d.png)

**Comment by fballs** [comment]
Fixed with !important declaration
